### ISSUE TITLE
Should be added to F-droid.org repository.

### ISSUE THREAD

**Issue by YiiKuoChong** [SebastianRask/Pocket-Plays-for-Twitch#1]
I actually thought that this app is a commercial, closed source app. It didn't say that it is a open-source app on Google Play either. I think it would be a great addition to the F-droid open source repository.

**Comment by szymon1749** [comment]
Szymon23081992@gmail.com

**Comment by anjandev** [comment]
this app requires google play services. That may be a problem for fdroid inclusion. See:
https://f-droid.org/en/docs/Inclusion_Policy/

However, I believe I can fork this and take out the google play dependancy and have the rest of the app work. I'll see what I can do.

**Comment by SebastianRask** [comment]
@anjandev Removing the Google Play dependency should be quite easy. Let me know if you encounter any issues.

Personally I do not want to support support multiple stores with different APK's. Closing this issue.

**Comment by Perflyst** [comment]
Seems like @anjandev never tried... I try right now and encounter following issue.
I cannot remove `com.google.android.gms:play-services-cast-framework:16.0.2` because than `androidx.mediarouter:mediarouter` is not available anymore.

**Comment by anjandev** [comment]
@Perflyst It's a bit more complex. You also have to remove the telemetry. I have it on my computer I just havent pushed anything cause I didnt get it to work.

Thanks for looking into it.

**Comment by Perflyst** [comment]
@SebastianRask would you please provide support on this?
I do not understand why do you have implemented google librarys. This app was a learning project and you probably created it for the use of yourself. No google playstore, no other app store.
So you implemented Google just to track you in your own app?

What does the (tracking) google libs do in the app? Are they really needed?

**Comment by SebastianRask** [comment]
@Perflyst When publishing the app to Google Play i added a few Google Analytics events to understand how people used the app and how many people dropped off during the onboarding and donation flow.

That is all it does.

I imagine the hard part is removing the casting support as it is a tightly coupled with the rest of the streaming and ui logic

**Comment by Perflyst** [comment]
Okay. Thanks, but still.. sad. This is the only app which is working great and has a very nice UI. There is no similar app available and also there is no Twitch client on f-droid (okay there is one but it is very old and needs vlc app too)

**Comment by ahkuma** [comment]
@Perflyst With a bit of work, I am sure it can be done.

**Comment by ahkuma** [comment]
Also @SebastianRask , it doesn't mean you need to maintain it. Maybe we could fork it, do some work and then push it upstream but maintain the downstream version for F-Droid.

**Comment by Perflyst** [comment]
Changing `applicationId` in /app/build.gradle kills the twitch login. I have replaced the API key with my own but still if there is not `net.nrask.notifyme` this is broken. Also replaced everything else with `net.nrask.notifyme` I have found (expect your third party lib srjneeds).

Can you tell me more about this? Does the applicationId somewhere has to be registered on twitch? (redirect_uri is changed)

**Comment by Perflyst** [comment]
https://gitlab.com/fdroid/fdroiddata/merge_requests/4662

--

You will not have any Twitch Chat if you don't log in but everything else works. I removed unused stuff and also dropped some permissions.

**Comment by testman42** [comment]
Even though this issue has been closed for some time, I  posting this for everyone who comes across it in the future:
Someone forked this and made it completely FOSS
https://github.com/Perflyst/Twire
And it is also on F-droid
https://f-droid.org/en/packages/com.perflyst.twire/
