### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by alexzorin** [SebastianRask/Pocket-Plays-for-Twitch#11]
Hey Sebastian,

This is my daily Twitch driver since a while (and it rocks) but could definitely do with some extra love. There's a few bugs and features that I'd love to write and send PRs for.

Would you be able to provide some help with build instructions and buildability in general?

Some of the first barriers I've run into are:

- Missing `google-services.json`
- Missing class `com.sebastianrask.bettersubscription.misc.SecretKeys`
- ...

Probably obvious why they are missing, but it also means building a development version isn't currently possible without some involved ripping out of Google's tendrils from the code.

Any help? Much appreciated!

**Comment by SebastianRask** [comment]
Hey there,

First of all, thank you for the nice words.

Very weird that SecretKeys.java has been removed. You can use this for development, though you will have to log into a twitch user and Chromecast is not supported:

`package com.sebastianrask.bettersubscription.misc;
/**
 * Created by sebastian on 24/07/2017.
    Add Keys
 */
public class SecretKeys {
    public static final String TWITCH_CLIENT_ID = "s9r26uney64y60m9g267600jb6n2lr";
    public static final String CHROME_CAST_APPLICATION_ID = "";
    public static final String IN_APP_PURCHASE_BASE64_KEY = ""; 
    public static final String NO_LOG_IN_ACCESS_TOKEN = "";
}`

I'll see what i can do about the missing `google-services.json` file.

**Comment by alexzorin** [comment]
Appreciate it! That did the trick.

Regarding `google-services.json`, I used the `google-services_old.json` file present in the `app/` directory and that seems to have gotten me where I needed to go.

**Comment by novatorem** [comment]
Can I ask what `NO_LOG_IN_ACCESS_TOKEN` is supposed to hold? Can I replace it with my own account's or did you get a token from twitch for general access?

**Comment by SebastianRask** [comment]
Sure you can replace it with an access token from your own account, but
that would make no difference if you are already signed in.

Since the Twitch api requires an access token, the value stored in this
constant will be used if no user is signed in.

**Comment by novatorem** [comment]
So when you did it yourself you just made a dummy account and that's the account being used when a user isn't logged in?

**Comment by SebastianRask** [comment]
Exactly
