### ISSUE TITLE
Stream not playing

### ISSUE THREAD

**Issue by maddawg836** [SebastianRask/Pocket-Plays-for-Twitch#28]
Hello,

When I opened a stream the past couple days, its says stream not live and just shows chat. This fixed itself eventually but has been back for a some time now (over a day). Did twitch change something that causes this more now?

Used to be isolated to some games\streams, but it happens on my phone which always worked as well.

Thanks.

**Comment by timwie** [comment]
Seems to be an issue with OAuth. I have found a [workaround](https://github.com/MrSprigster/Twitch-on-Kodi/issues/461#issuecomment-552035680) for the other third party client I use, which is Twitch-on-Kodi. Twitch apparently is [periodically blocking every client ID but their own](https://github.com/MrSprigster/Twitch-on-Kodi/issues/461#issuecomment-552646788), so every client is affected. The discussion [over at streamlink](https://github.com/streamlink/streamlink/issues/2680#issuecomment-552024753) has more info, but there doesn't seem to be a fix for now.

**Comment by SebastianRask** [comment]
I say that thread as well.
Seems like the only workaround is using Twitch's own client ID, to prevent
being blocked.

**Comment by SebastianRask** [comment]
Fixed in 1.8.4
