### ISSUE TITLE
possible Twitch API change

### ISSUE THREAD

**Issue by digital-mystik** [SebastianRask/Pocket-Plays-for-Twitch#29]
Hello,

I noticed that "my streams" are not loading currently when logged in. There is a similar issue with another 3rd party client as well, so I'm guessing it's an API issue or something along those lines.. or maybe it's just me.

**Comment by SebastianRask** [comment]
Not just you. network calls to /streams/followed are returning 401 unauthorized. I am wondering if Twitch has started blocking this endpoint for Pocket Plays. According to the documentation the oauth token has the correct scopes.

**Comment by SebastianRask** [comment]
This has been fixed with 1.8.4
