### ISSUE TITLE
Ads are now playing again

### ISSUE THREAD

**Issue by Maxwell12347842** [SebastianRask/Pocket-Plays-for-Twitch#33]
you start a stream, Pocket Plays now displays "Advertisement is playing" for 30 seconds. it's not a "real" advertisement, but a message you can't skip and you need to wait the 30 seconds till you can watch a stream. this is really annoying and everytime you click it away you need to wait again and again and again..

ublock origin and browser adblockers doesn't have that issue.. could you please fix it so it blocks again?

**Comment by Maxwell12347842** [comment]
update: now streams are not playing at all anymore.

**Comment by SebastianRask** [comment]
Thanks for reporting and updating. Unfortunately there is not much the app can do to filter out the apps, as they are directly embeded into the HLS stream.,
