### ISSUE TITLE
Disable Pocket Plays won't run without Google Play services popup

### ISSUE THREAD

**Issue by ptkovsky** [SebastianRask/Pocket-Plays-for-Twitch#5]
This follows me from the start and every next screen or whatever action. I don't have any of that installed and this app runs fine except of this annoying popup. Tested official Twitch app and it behaves the same. But can we fix this here please?

**Comment by SebastianRask** [comment]
Unfortunately I do not control the behavior of the pop up. It might seem like that Google Play Services isn't used, but it is used in the background for a couple of things.

You can take a look at https://github.com/anjandev/Pocket-Plays-for-Twitch if you are interested in a version without Google Services. I'm unsure about the state of this fork though.

**Comment by ptkovsky** [comment]
That services aren't being used at least in my case because I didn't install any of them. Running SAOSP without any of the GApps on it. Yeah this looks like an API thing that seems hard to control. Whatever... The fork looks really out of date but thanks for the link!
