### ISSUE TITLE
No Playback Android 5.x

### ISSUE THREAD

**Issue by maddawg836** [SebastianRask/Pocket-Plays-for-Twitch#9]
Hello,

Thanks for your hard work in fixing the emotes issue! I noticed someone else on the play store had an issue with playback on version 5 of android. I'm on 5.1.1 and it seems like certain streams just dont want to load. It says stream no longer live,  but it connects to chat and I can watch it from twitch app. happens to a majority of streams, but some do still work.

Hope you can help again!

Thanks.

**Comment by SebastianRask** [comment]
Hey there, I started roll out of an update yesterday that should fix this issue - Did you update or is this issue still present?

**Comment by maddawg836** [comment]
I have just reinstalled to be certain, I'm on 1.8.1. Streams/games don't generate thumbnails most of the time (also on my phone too so might be twitch side since only started today). The "stream no longer live" message comes up after the stream attempts to load about 15 seconds, before it would give the error right away. Chat does load normally.

Another strange thing is that I can load just about any stream in the game for "Hearthstone". I tried about 10 in that category and they all worked.

**Comment by SebastianRask** [comment]
I am experiencing something strange on Android 5.x - It seems that it is only the 'auto' video quality that is not working - Do you experience the same?

**Comment by derrod** [comment]
To follow up on this: the reason for this is likely that Twitch has decided to add the game name to the token that is used to authenticate with the usher service. If the game name contains special characters or spaces those are not correctly escaped resulting in playback failing. Funnily enough it also happens in some official Twitch apps: https://www.reddit.com/r/Twitch/comments/9xjp0s/why_can_pokemon_games_not_be_watched_on_ps4/

**Comment by maddawg836** [comment]
This happened on the pokemon stream! It says it ended and the only option is on the quality is auto. Hopefully they realize and fix it. Thanks for the update derrod!
